# Generated by Django 6.0.6 on 2026-07-25 01:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('Candidate', 'Candidate'), ('Employer', 'Employer'), ('Admin', 'Admin')], max_length=15)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('is_staff', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Entry level', 'Entry level'), ('Junior', 'Junior'), ('Mid level', 'Mid level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Expert', 'Expert')], null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='Cvs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_url', models.FileField(max_length=500, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('candidate', models.ForeignKey(blank=True, db_column='candidate_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='jobs.candidates')),
            ],
            options={
                'db_table': 'cvs',
            },
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.companies')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employers',
            },
        ),
        migrations.CreateModel(
            name='JobOffers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Seasonal', 'Seasonal'), ('Volunteer', 'Volunteer')])),
                ('experience_level', models.CharField(choices=[('Intern', 'Intern'), ('Entry level', 'Entry level'), ('Junior', 'Junior'), ('Mid level', 'Mid level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Expert', 'Expert')])),
                ('contract_type', models.CharField(choices=[('B2b', 'B2b'), ('Employment contract', 'Employment contract'), ('Contract of mandate', 'Contract of mandate'), ('Contract for specific work', 'Contract for specific work')])),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Onsite', 'Onsite')])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed'), ('Expired', 'Expired')])),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.companies')),
                ('employer', models.ForeignKey(blank=True, db_column='employer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employers')),
            ],
            options={
                'db_table': 'job_offers',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('pk', models.CompositePrimaryKey('job_offer', 'candidate', 'cv', blank=True, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.candidates')),
                ('cv', models.ForeignKey(db_column='cv_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.cvs')),
                ('job_offer', models.ForeignKey(db_column='job_offer_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.joboffers')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('pk', models.CompositePrimaryKey('candidate', 'job_offer', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.candidates')),
                ('job_offer', models.ForeignKey(db_column='job_offer_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.joboffers')),
            ],
            options={
                'db_table': 'saved_jobs',
            },
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['Candidate', 'Employer', 'Admin'])), name='users_role_check'),
        ),
        migrations.AddConstraint(
            model_name='candidates',
            constraint=models.CheckConstraint(condition=models.Q(('experience_level__isnull', True), ('experience_level__in', ['Intern', 'Entry level', 'Junior', 'Mid level', 'Senior', 'Lead', 'Expert']), _connector='OR'), name='candidates_experience_level_check'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('employment_type__in', ['Full-time', 'Part-time', 'Contract', 'Temporary', 'Internship', 'Seasonal', 'Volunteer'])), name='job_offers_employment_type_check'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('experience_level__in', ['Intern', 'Entry level', 'Junior', 'Mid level', 'Senior', 'Lead', 'Expert'])), name='job_offers_experience_level_check'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('contract_type__in', ['B2b', 'Employment contract', 'Contract of mandate', 'Contract for specific work'])), name='job_offers_contract_type_check'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('work_mode__in', ['Remote', 'Hybrid', 'Onsite'])), name='job_offers_work_mode_check'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Draft', 'Active', 'Closed', 'Expired'])), name='job_offers_status_check'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__gte', 0)), name='salary_min_pos'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('salary_max__gte', models.F('salary_min'))), name='salary_max_pos'),
        ),
        migrations.AddConstraint(
            model_name='joboffers',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='expires_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='applications',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Sent', 'Reviewed', 'Rejected', 'Accepted'])), name='applications_status_check'),
        ),
    ]
